### ISSUE TITLE
Unable to parse rss feed

### ISSUE THREAD

**Issue by vflash** [nikku/easysax#8]
No namespace for the root element

example https://lenta.ru/rss
```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
  ...
```

**Comment by nikku** [comment]
Is the document valid XML? If not, the parse error is correct, right?

----

__Edit__: Verified parser behavior: https://github.com/nikku/saxen/commit/fca2e9daa5325a8e577b29720cbe9944934250c6.

The root tag does not declare namespace information and is imported without a namespace because of that. Looks good to me.

Do you expect anything else?
